alias ls='eza --icons --group-directories-first'
alias ll='eza -lh --icons'          # detailed list
alias la='eza -a --icons'           # with hidden files
alias lt='eza --tree --icons'       # tree output
alias c='clear'
alias ..='cd ..'